version: '3.8'

services:
  warpio-net:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warpio-net
    restart: unless-stopped
    ports:
      - "5015:5015"
    environment:
      - NODE_ENV=production
      - PORT=5015
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - WARPIO_SESSION_SECRET=${WARPIO_SESSION_SECRET:-warpio-secret-change-me}
      - WARPIO_DATA_DIR=/app/data
    volumes:
      # Persistent storage for user data
      - warpio_data:/app/data
      # Optional: Mount host directory for user workspaces
      - ${WARPIO_WORKSPACES_DIR:-./workspaces}:/workspaces
    networks:
      - warpio-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5015/api/auth/setup-status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: warpio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - warpio-net
    networks:
      - warpio-net
    profiles:
      - production

volumes:
  warpio_data:
    driver: local

networks:
  warpio-net:
    driver: bridge